import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ListViewGettingStartedComponent } from './getting-started/listview-getting-started.component';
import { ListViewGettingStartedHorizontalComponent } from './getting-started-horizontal/listview-getting-started-horizontal.component';
import { ListViewHeaderFooterComponent } from './header-footer/auto-size/listview-auto-size.component';
import { ListViewBigFooterComponent } from './header-footer/big-footer/listview-big-footer.component';
import { ListviewChangeSizeAtRuntimeComponent } from './header-footer/change-size-at-runtime/listview-change-size-at-runtime.component';
import { ListViewBigHeaderComponent } from './header-footer/big-header/listview-big-header.component';
import { ListViewItemAnimationsComponent } from './item-animations/listview-item-animations.component';
import { ListViewItemLayoutsGridComponent } from './item-layouts/listview-item-layouts-grid.component';
import { ListViewItemLayoutsGridNoHeightComponent } from './item-layouts/listview-item-layouts-grid-no-height.component';
import { ListViewItemLayoutsLinearComponent } from './item-layouts/listview-item-layouts-linear.component';
import { ListViewItemLayoutsRuntimeComponent } from './item-layouts/listview-item-layouts-runtime.component';
import { ListViewItemLayoutsStaggeredComponent } from './item-layouts/listview-item-layouts-staggered.component';
import { ListViewItemLoadingComponent } from './item-loading/listview-item-loading.component';
import { ListViewItemReorderComponent } from './item-reorder/listview-item-reorder.component';
import { ListViewItemReorderHandleComponent } from './item-reorder/listview-item-reorder-handle.component';
import { ListViewItemSelectionMultipleComponent } from './item-selection/listview-item-selection-multiple.component';
import { ListViewItemSelectionProgrammaticComponent } from './item-selection/listview-item-selection-programmatic.component';
import { ListViewItemSelectionComponent } from './item-selection/listview-item-selection.component';
import { ListViewItemSeparatorComponent } from './item-separator/listview-item-separator.component';
import { ListViewDynamicSizeAutoComponent } from './load-on-demand/dynamic-size-auto/listview-dynamic-size-auto.component';
import { ListViewDynamicSizeManualComponent } from './load-on-demand/dynamic-size-manual/listview-dynamic-size-manual.component';
import { ListViewFixedSizeAutoComponent } from './load-on-demand/fixed-size-auto/listview-fixed-size-auto.component';
import { ListViewFixedSizeAutoWithSmallSourceComponent } from './load-on-demand/fixed-size-auto-with-small-source/listview-fixed-size-auto-with-small-source.component';
import { ListViewFixedSizeManualComponent } from './load-on-demand/fixed-size-manual/listview-fixed-size-manual.component';
import { ListViewMultipleTemplatesComponent } from './multiple-templates/listview-multiple-templates.component';
import { ListViewObservableArrayComponent } from './observable-array/listview-observable-array.component';
import { ListViewPullToRefreshComponent } from './pull-to-refresh/getting-started/listview-pull-to-refresh.component';
import { ListViewPullToRefreshCustomizeComponent } from './pull-to-refresh/customize/listview-pull-to-refresh-customize.component';
import { ListViewScrollEventsComponent } from './scroll-events/listview-scroll-events.component';
import { ListViewScrollToIndexHorizontalComponent } from './scroll-to-index/listview-scroll-to-index-horizontal.component';
import { ListViewScrollToIndexVerticalComponent } from './scroll-to-index/listview-scroll-to-index-vertical.component';
import { ListViewScrollToIndexInitialComponent } from './scroll-to-index/listview-scroll-to-index-initial.component';
import { ListViewSelectionStatesComponent } from './selection-states/listview-selection-states.component';
import { ListViewSwipeActionsMultipleComponent } from './swipe-actions/listview-swipe-actions-multiple.component';
import { ListViewSwipeActionsThresholdsComponent } from './swipe-actions/listview-swipe-actions-thresholds.component';
import { ListViewSwipeActionsComponent } from './swipe-actions/listview-swipe-actions.component';
import { ListViewSwipeDisableComponent } from './swipe-actions/listview-swipe-disable.component';
import { ListViewDataOperationsFilteringComponent } from './filtering/listview-data-operations-filtering.component';
import { ListViewDataOperationsGroupingComponent } from './grouping/listview-data-operations-grouping.component';
import { ListViewDataOperationsGroupingHeaderFooterComponent } from './grouping-with-header-footer/with-header-footer.component';
import { ListViewDataOperationsGroupingTemplatesComponent } from './grouping-multiple-templates/listview-data-operations-grouping-templates.component';
import { ListviewDataOperationsGroupingCollapsibleComponent } from './grouping-collapsible/listview-data-operations-grouping-collapsible.component';
import { ListViewDataOperationsGroupingScrollToComponent } from './grouping-scroll-to/grouping-scroll-to.component';
import { ListViewDataOperationsMultipleComponent } from './multiple-operations/listview-data-operations-multiple.component';
import { ListViewDataOperationsMultipleWithSwipeComponent } from './multiple-operations-with-swipe/listview-multiple-operations-with-swipe.component';
import { ListViewDataOperationsSortingComponent } from './sorting/listview-data-operations-sorting.component';
import { ListViewWithBigDataComponent } from './with-big-data/listview-with-big-data.component';
import { ListviewHorizontalWithVariableItemWidthComponent } from './horizontal-with-variable-item-width/listview-horizontal-with-variable-item-width.component';
import { ListViewGroupSwipeLoadPullComponent } from './group-swipe-load-pull/listview-group-swipe-load-pull.component';
import { ListViewFirstVisibleIndexComponent } from './first-visible-index/first-visible-index.component';
import { ListviewCompTemplateComponent } from "./custom-angular-comp/listview-comp-template.component";

export const routes: Routes = [
  { path: 'ListViewGettingStartedComponent', component: ListViewGettingStartedComponent },
  { path: 'ListViewGettingStartedHorizontalComponent', component: ListViewGettingStartedHorizontalComponent },
  { path: 'ListViewHeaderFooterComponent', component: ListViewHeaderFooterComponent },
  { path: 'ListViewBigFooterComponent', component: ListViewBigFooterComponent },
  { path: 'ListviewChangeSizeAtRuntimeComponent', component: ListviewChangeSizeAtRuntimeComponent },
  { path: 'ListViewBigHeaderComponent', component: ListViewBigHeaderComponent },
  { path: 'ListViewItemAnimationsComponent', component: ListViewItemAnimationsComponent },
  { path: 'ListViewItemLayoutsGridComponent', component: ListViewItemLayoutsGridComponent },
  { path: 'ListViewItemLayoutsGridNoHeightComponent', component: ListViewItemLayoutsGridNoHeightComponent },
  { path: 'ListViewItemLayoutsLinearComponent', component: ListViewItemLayoutsLinearComponent },
  { path: 'ListViewItemLayoutsRuntimeComponent', component: ListViewItemLayoutsRuntimeComponent },
  { path: 'ListViewItemLayoutsStaggeredComponent', component: ListViewItemLayoutsStaggeredComponent },
  { path: 'ListViewItemLoadingComponent', component: ListViewItemLoadingComponent },
  { path: 'ListViewItemReorderComponent', component: ListViewItemReorderComponent },
  { path: 'ListViewItemReorderHandleComponent', component: ListViewItemReorderHandleComponent },
  { path: 'ListViewItemSelectionMultipleComponent', component: ListViewItemSelectionMultipleComponent },
  { path: 'ListViewItemSelectionProgrammaticComponent', component: ListViewItemSelectionProgrammaticComponent },
  { path: 'ListViewItemSelectionComponent', component: ListViewItemSelectionComponent },
  { path: 'ListViewItemSeparatorComponent', component: ListViewItemSeparatorComponent },
  { path: 'ListViewDynamicSizeAutoComponent', component: ListViewDynamicSizeAutoComponent },
  { path: 'ListViewDynamicSizeManualComponent', component: ListViewDynamicSizeManualComponent },
  { path: 'ListViewFixedSizeAutoComponent', component: ListViewFixedSizeAutoComponent },
  { path: 'ListViewFixedSizeAutoWithSmallSourceComponent', component: ListViewFixedSizeAutoWithSmallSourceComponent },
  { path: 'ListViewFixedSizeManualComponent', component: ListViewFixedSizeManualComponent },
  { path: 'ListViewMultipleTemplatesComponent', component: ListViewMultipleTemplatesComponent },
  { path: 'ListViewObservableArrayComponent', component: ListViewObservableArrayComponent },
  { path: 'ListViewPullToRefreshComponent', component: ListViewPullToRefreshComponent },
  { path: 'ListViewPullToRefreshCustomizeComponent', component: ListViewPullToRefreshCustomizeComponent },
  { path: 'ListViewScrollEventsComponent', component: ListViewScrollEventsComponent },
  { path: 'ListViewScrollToIndexHorizontalComponent', component: ListViewScrollToIndexHorizontalComponent },
  { path: 'ListViewScrollToIndexVerticalComponent', component: ListViewScrollToIndexVerticalComponent },
  { path: 'ListViewSelectionStatesComponent', component: ListViewSelectionStatesComponent },
  { path: 'ListViewSwipeActionsMultipleComponent', component: ListViewSwipeActionsMultipleComponent },
  { path: 'ListViewSwipeActionsThresholdsComponent', component: ListViewSwipeActionsThresholdsComponent },
  { path: 'ListViewSwipeActionsComponent', component: ListViewSwipeActionsComponent },
  { path: 'ListViewSwipeDisableComponent', component: ListViewSwipeDisableComponent },
  { path: 'ListViewScrollToIndexInitialComponent', component: ListViewScrollToIndexInitialComponent },
  { path: 'ListViewDataOperationsFilteringComponent', component: ListViewDataOperationsFilteringComponent },
  { path: 'ListViewDataOperationsGroupingComponent', component: ListViewDataOperationsGroupingComponent },
  { path: 'ListViewDataOperationsGroupingHeaderFooterComponent', component: ListViewDataOperationsGroupingHeaderFooterComponent },
  { path: 'ListViewDataOperationsGroupingTemplatesComponent', component: ListViewDataOperationsGroupingTemplatesComponent },
  { path: 'ListviewDataOperationsGroupingCollapsibleComponent', component: ListviewDataOperationsGroupingCollapsibleComponent },
  { path: 'ListViewDataOperationsGroupingScrollToComponent', component: ListViewDataOperationsGroupingScrollToComponent },
  { path: 'ListViewDataOperationsMultipleComponent', component: ListViewDataOperationsMultipleComponent },
  { path: 'ListViewDataOperationsMultipleWithSwipeComponent', component: ListViewDataOperationsMultipleWithSwipeComponent },
  { path: 'ListViewDataOperationsSortingComponent', component: ListViewDataOperationsSortingComponent },
  { path: 'ListViewWithBigDataComponent', component: ListViewWithBigDataComponent },
  { path: 'ListviewHorizontalWithVariableItemWidthComponent', component: ListviewHorizontalWithVariableItemWidthComponent },
  { path: 'ListViewGroupSwipeLoadPullComponent', component: ListViewGroupSwipeLoadPullComponent },
  { path: 'ListViewFirstVisibleIndexComponent', component: ListViewFirstVisibleIndexComponent },
  { path: 'ListviewCompTemplateComponent', component: ListviewCompTemplateComponent }
];