import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ListViewGettingStartedComponent } from './getting-started/listview-getting-started.component';
import { ListViewHeaderFooterComponent } from './header-footer/listview-header-footer.component';
import { ListViewItemAnimationsComponent } from './item-animations/listview-item-animations.component';
import { ListViewItemLayoutsGridComponent } from './item-layouts/listview-item-layouts-grid.component';
import { ListViewItemLayoutsLinearComponent } from './item-layouts/listview-item-layouts-linear.component';
import { ListViewItemLayoutsRuntimeComponent } from './item-layouts/listview-item-layouts-runtime.component';
import { ListViewItemLayoutsStaggeredComponent } from './item-layouts/listview-item-layouts-staggered.component';
import { ListViewItemLoadingComponent } from './item-loading/listview-item-loading.component';
import { ListViewItemReorderComponent } from './item-reorder/listview-item-reorder.component';
import { ListViewItemReorderHandleComponent } from './item-reorder/listview-item-reorder-handle.component';
import { ListViewItemSelectionMultipleComponent } from './item-selection/listview-item-selection-multiple.component';
import { ListViewItemSelectionProgrammaticComponent } from './item-selection/listview-item-selection-programmatic.component';
import { ListViewItemSelectionComponent } from './item-selection/listview-item-selection.component';
import { ListViewItemSeparatorComponent } from './item-separator/listview-item-separator.component';
import { ListViewLoadOnDemandComponent } from './load-on-demand/listview-load-on-demand.component';
import { ListViewMultipleTemplatesComponent } from './multiple-templates/listview-multiple-templates.component';
import { ListViewObservableArrayComponent } from './observable-array/listview-observable-array.component';
import { ListViewPullToRefreshComponent } from './pull-to-refresh/listview-pull-to-refresh.component';
import { ListViewScrollEventsComponent } from './scroll-events/listview-scroll-events.component';
import { ListViewScrollToIndexHorizontalComponent } from './scroll-to-index/listview-scroll-to-index-horizontal.component';
import { ListViewScrollToIndexVerticalComponent } from './scroll-to-index/listview-scroll-to-index-vertical.component';
import { ListViewSelectionStatesComponent } from './selection-states/listview-selection-states.component';
import { ListViewSwipeActionsMultipleComponent } from './swipe-actions/listview-swipe-actions-multiple.component';
import { ListViewSwipeActionsThresholdsComponent } from './swipe-actions/listview-swipe-actions-thresholds.component';
import { ListViewSwipeActionsComponent } from './swipe-actions/listview-swipe-actions.component';
import { ListViewSwipeDisableComponent } from './swipe-actions/listview-swipe-disable.component';

export const routes: Routes = [
  { path: 'ListViewGettingStartedComponent', component: ListViewGettingStartedComponent },
  { path: 'ListViewHeaderFooterComponent', component: ListViewHeaderFooterComponent },
  { path: 'ListViewItemAnimationsComponent', component: ListViewItemAnimationsComponent },
  { path: 'ListViewItemLayoutsGridComponent', component: ListViewItemLayoutsGridComponent },
  { path: 'ListViewItemLayoutsLinearComponent', component: ListViewItemLayoutsLinearComponent },
  { path: 'ListViewItemLayoutsRuntimeComponent', component: ListViewItemLayoutsRuntimeComponent },
  { path: 'ListViewItemLayoutsStaggeredComponent', component: ListViewItemLayoutsStaggeredComponent },
  { path: 'ListViewItemLoadingComponent', component: ListViewItemLoadingComponent },
  { path: 'ListViewItemReorderComponent', component: ListViewItemReorderComponent },
  { path: 'ListViewItemReorderHandleComponent', component: ListViewItemReorderHandleComponent },
  { path: 'ListViewItemSelectionMultipleComponent', component: ListViewItemSelectionMultipleComponent },
  { path: 'ListViewItemSelectionProgrammaticComponent', component: ListViewItemSelectionProgrammaticComponent },
  { path: 'ListViewItemSelectionComponent', component: ListViewItemSelectionComponent },
  { path: 'ListViewItemSeparatorComponent', component: ListViewItemSeparatorComponent },
  { path: 'ListViewLoadOnDemandComponent', component: ListViewLoadOnDemandComponent },
  { path: 'ListViewMultipleTemplatesComponent', component: ListViewMultipleTemplatesComponent },
  { path: 'ListViewObservableArrayComponent', component: ListViewObservableArrayComponent },
  { path: 'ListViewPullToRefreshComponent', component: ListViewPullToRefreshComponent },
  { path: 'ListViewScrollEventsComponent', component: ListViewScrollEventsComponent },
  { path: 'ListViewScrollToIndexHorizontalComponent', component: ListViewScrollToIndexHorizontalComponent },
  { path: 'ListViewScrollToIndexVerticalComponent', component: ListViewScrollToIndexVerticalComponent },
  { path: 'ListViewSelectionStatesComponent', component: ListViewSelectionStatesComponent },
  { path: 'ListViewSwipeActionsMultipleComponent', component: ListViewSwipeActionsMultipleComponent },
  { path: 'ListViewSwipeActionsThresholdsComponent', component: ListViewSwipeActionsThresholdsComponent },
  { path: 'ListViewSwipeActionsComponent', component: ListViewSwipeActionsComponent },
  { path: 'ListViewSwipeDisableComponent', component: ListViewSwipeDisableComponent }
];