import { ModuleWithProviders } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { DataFormAdjustmentComponent } from './adjustment/dataform-adjustment.component';
import { DataFormCommitModesComponent } from './commit-modes/dataform-commit-modes.component';
import { DataFormaAutoCompleteComponent } from './editors/autocomplete/dataform-autocomplete.component';
import { DataformCustomEditorsComponent } from './editors/custom-editors/dataform-custom-editors.component';
import { DataFormLabelsComponent } from './editors/labels/dataform-labels.component';
import { DataformReadOnlyComponent } from './editors/readonly/dataform-read-only.component';
import { DataFormEditorsComponent } from './editors/dataform-editors.component';
import { DataFormEventsComponent } from './events/dataform-events.component';
import { DataFormGettingStartedComponent } from './getting-started/dataform-getting-started.component';
import { DataformGettingStartedJsonComponent } from './getting-started-json/dataform-getting-started-json.component';
import { DataFormGroupsComponent } from './groups/dataform-groups.component';
import { DataformImageLabelsComponent } from './image-labels/dataform-image-labels.component';
import { DataformGridLayoutComponent } from './layouts/dataform-grid-layout.component';
import { DataformStackLayoutComponent } from './layouts/dataform-stack-layout.component';
import { DataFormPlatformSpecificsComponent } from './platform-specifics/dataform-platform-specifics.component';
import { DataformPropertiesJsonComponent } from './properties-json/dataform-properties-json.component';
import { DataFormRuntimeUpdatesComponent } from './runtime-updates/dataform-runtime-updates.component';
import { DataFormScrollingComponent } from './scrolling/dataform-scrolling.component';
import { DataformStylingAdvancedComponent } from './styling/advanced/dataform-styling-advanced.component';
import { DataFormStylingComponent } from './styling/common/dataform-styling.component';
import { DataFormEditorBackgroundComponent } from './styling/editor-background/dataform-editor-background.component';
import { DataformEditorStyleComponent } from './styling/editor-style/dataform-editor-style.component';
import { DataFormAsyncValidationComponent } from './validation/async-validation/dataform-async-validation.component';
import { DataformCheckErrorsComponent } from './validation/check-errors/dataform-check-errors.component';
import { DataFormCustomValidationComponent } from './validation/custom-validation/dataform-custom-validation.component';
import { DataFormCustomValidatorComponent } from './validation/custom-validator/dataform-custom-validator.component';
import { DataFormValidationMetadataComponent } from './validation/metadata/dataform-validation-metadata.component';
import { DataFormValidationEventsComponent } from './validation/validation-events/dataform-validation-events.component';
import { DataFormValidationModesComponent } from './validation/validation-modes/dataform-validation-modes.component';
import { DataFormValidationComponent } from './validation/dataform-validation.component';
import { DataFormValueProvidersComponent } from './value-providers/dataform-value-providers.component';

export const routes: Routes = [
  { path: 'DataFormAdjustmentComponent', component: DataFormAdjustmentComponent },
  { path: 'DataFormCommitModesComponent', component: DataFormCommitModesComponent },
  { path: 'DataFormaAutoCompleteComponent', component: DataFormaAutoCompleteComponent },
  { path: 'DataformCustomEditorsComponent', component: DataformCustomEditorsComponent },
  { path: 'DataFormLabelsComponent', component: DataFormLabelsComponent },
  { path: 'DataformReadOnlyComponent', component: DataformReadOnlyComponent },
  { path: 'DataFormEditorsComponent', component: DataFormEditorsComponent },
  { path: 'DataFormEventsComponent', component: DataFormEventsComponent },
  { path: 'DataFormGettingStartedComponent', component: DataFormGettingStartedComponent },
  { path: 'DataformGettingStartedJsonComponent', component: DataformGettingStartedJsonComponent },
  { path: 'DataFormGroupsComponent', component: DataFormGroupsComponent },
  { path: 'DataformImageLabelsComponent', component: DataformImageLabelsComponent },
  { path: 'DataformGridLayoutComponent', component: DataformGridLayoutComponent },
  { path: 'DataformStackLayoutComponent', component: DataformStackLayoutComponent },
  { path: 'DataFormPlatformSpecificsComponent', component: DataFormPlatformSpecificsComponent },
  { path: 'DataformPropertiesJsonComponent', component: DataformPropertiesJsonComponent },
  { path: 'DataFormRuntimeUpdatesComponent', component: DataFormRuntimeUpdatesComponent },
  { path: 'DataFormScrollingComponent', component: DataFormScrollingComponent },
  { path: 'DataformStylingAdvancedComponent', component: DataformStylingAdvancedComponent },
  { path: 'DataFormStylingComponent', component: DataFormStylingComponent },
  { path: 'DataFormEditorBackgroundComponent', component: DataFormEditorBackgroundComponent },
  { path: 'DataformEditorStyleComponent', component: DataformEditorStyleComponent },
  { path: 'DataFormAsyncValidationComponent', component: DataFormAsyncValidationComponent },
  { path: 'DataformCheckErrorsComponent', component: DataformCheckErrorsComponent },
  { path: 'DataFormCustomValidationComponent', component: DataFormCustomValidationComponent },
  { path: 'DataFormCustomValidatorComponent', component: DataFormCustomValidatorComponent },
  { path: 'DataFormValidationMetadataComponent', component: DataFormValidationMetadataComponent },
  { path: 'DataFormValidationEventsComponent', component: DataFormValidationEventsComponent },
  { path: 'DataFormValidationModesComponent', component: DataFormValidationModesComponent },
  { path: 'DataFormValidationComponent', component: DataFormValidationComponent },
  { path: 'DataFormValueProvidersComponent', component: DataFormValueProvidersComponent },
];